---

- name: nfs directory
  file:
    path: /srv/nfs
    state: directory

- name: enable nfs
  shell: |
    systemctl  enable nfs-server
    systemctl  start nfs-server

#- name: create physical volume
#  shell: pvcreate /srv/nfs

#- name: Crea volumen group
#  lvg:
#      vg: vg-nfs
#      pvs: /srv/nfs

#- name: create logical volume
#  lvol:
#    vg: vg-nfs
#    lv: lv-nfs
#    size: 100%FREE

#- name:  create xfs filesystem
#  filesystem:
#    fstype: xfs
#    dev: /dev/vg-nfs/lv-nfs

#- name: create directory
#  file:
#    path: /srv/nfs
#    state: directory

#- name: mounting it
#  mount:
#    src: /dev/vg-nfs/lv-nfs
#    path: /srv/nfs 
#    fstype: xfs
#    state: mounted

- name: exportfs accepts LAN
  become: true
  ansible.builtin.lineinfile:
    path: /etc/exports
    backup: yes
    line: "{{item}}"
    create: yes
    state: present
  loop:
  - /srv/nfs {{ip_worker01}}(rw,sync,insecure,fsid=0,no_subtree_check,no_root_squash)
  - /srv/nfs {{ip_worker02}}(rw,sync,insecure,fsid=0,no_subtree_check,no_root_squash)
  - /srv/nfs {{ip_master}}(rw,sync,insecure,fsid=0,no_subtree_check,no_root_squash)
  - /srv/nfs {{ip_cidr}}(rw,sync,insecure,fsid=0,no_subtree_check,no_root_squash)
  register: exportfs
  async: 10
  poll: 2

- name: apply changes
  shell: |
    exportfs -r
    exportfs -s

- name: firewall rules nfs
  shell: |
    firewall-cmd --permanent --add-service=nfs
    firewall-cmd --permanent --add-service=rpc-bind
    firewall-cmd --permanent --add-service=mountd
    firewall-cmd --reload