---

- name: nfs directory
  file:
    path: /srv/nfs
    state: directory

- name: enable nfs
  shell: |
    systemctl  enable nfs-server
    systemctl  start nfs-server

- name: exports accepts LAN
  become: true
  ansible.builtin.lineinfile:
    path: /etc/exports
    backup: yes
    line: "{{item}}"
    create: yes
    state: present
  loop:
  - /srv/nfs {{ip_worker01}}(rw,sync,insecure,fsid=0,no_subtree_check,no_root_squash)
  - /srv/nfs {{ip_worker02}}(rw,sync,insecure,fsid=0,no_subtree_check,no_root_squash)
  - /srv/nfs {{ip_master}}(rw,sync,insecure,fsid=0,no_subtree_check,no_root_squash)
  - /srv/nfs {{ip_cidr}}(rw,sync,insecure,fsid=0,no_subtree_check,no_root_squash)
  register: exportfs
  async: 10
  poll: 2

- name: apply changes
  shell: |
    exportfs -r
    exportfs -s

- name: firewall rules nfs
  shell: |
    firewall-cmd --permanent --add-service=nfs
    firewall-cmd --permanent --add-service=rpc-bind
    firewall-cmd --permanent --add-service=mountd
    firewall-cmd --reload