---

docker_repo: https://download.docker.com/linux/centos/docker-ce.repo
docker_version: 20.10.6-3.el8

ip_master: '10.0.1.55'
ip_worker01: '10.0.1.10'
ip_worker02: '10.0.1.11'

ip_cidr: '10.10.0.0/16'
ip_cidr_subnet: '10.10.1.0/24'

