- name: repo k8s
  copy: 
    dest: "/etc/yum.repos.d/kubernetes.repo"
    content: |
      [kubernetes]
      name=Kubernetes
      baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
      enabled=1
      gpgcheck=1
      repo_gpgcheck=1
      gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
      exclude=kubelet kubeadm kubectl

- name: setup kubeadm, kubectl and kubelet
  dnf:
    name:
      - kubeadm
      - kubectl
      - kubelet
    disable_excludes: kubernetes

- name: enables kubelet
  ansible.builtin.systemd:
    name: kubelet
    enabled: yes
    state: started