- name: enable firewall
  ansible.builtin.systemd:
    name: firewalld
    enabled: yes
    state: started

- name: enable br_netfinder
  modprobe:
    name: br_netfilter
    state: present

- name: firewall masquerade
  ansible.posix.firewalld:
   masquerade: enabled
   state: enabled
   permanent: yes
   zone: dmz

- name: reload firewall
  systemd:
    name: firewalld
    state: reloaded

- name: k8s firewall traffic
  copy:
    dest: /etc/sysctl.d/k8s.conf
    content:
      net.bridge.bridge-nf-call-ip6tables = 1
      net.bridge.bridge-nf-call-iptables = 1

- name: apply changes
  become: true
  command: sysctl --system

- name: disable swap
  become: true
  shell: swapoff -a

- name: delete swap fstab
  become: true
  ansible.builtin.lineinfile:
    path: /etc/fstab
    regexp: "swap" 
    state: absent
    backup: yes