- name: chrony setup 
  dnf:
    name: chrony
    state: latest

- name: enable chronyd
  systemd:
   name: chronyd
   state: started
   enabled: yes

- name: set ntp
  shell: |
         timedatectl set-ntp true

- name: Establece la zona horaria
  timezone:
    name: "{{timezone}}"