- name: configuring ports
  firewalld:
    permanent: yes
    immediate: yes
    state: enabled
    port: "{{item}}"
  loop:
   - 10250/tcp
   - 30000-32767/tcp
   
- name: reload firewallid
  systemd:
    name: firewalld
    state: reloaded

- name: avoid kubeadm failing to initialize next step
  shell: echo 1 > /proc/sys/net/ipv4/ip_forward

- name: copy join from local to workers
  copy: src=join-command dest=/tmp/join-command.sh mode=0777

- name: join workers to k8s cluster
  command: sh /tmp/join-command.sh

- name: remove join-command
  command: rm join-command