- name: configuring ports
  firewalld:
    permanent: yes
    immediate: yes
    state: enabled
    port: "{{item}}"
  loop:
   - 10250/tcp
   - 30000-32767/tcp
   
- name: reload firewallid
  systemd:
    name: firewalld
    state: reloaded

- name: avoid kubeadm failing to initialize next step
  shell: echo 1 > /proc/sys/net/ipv4/ip_forward

- name: join node
  shell: |
    kubeadm reset -f
    cat token_kube | tail -2 > initoken.sh
    sh initoken.sh