- name: create mamespace
  become: true
  shell: kubectl create namespace webapp-volumes


- name: Copy nfs-pv.yaml to master
  ansible.builtin.copy:
   src: nfs-pv.yaml
   dest: ./
   mode: u=rw,g=r,o=r

- name: Apply nfs-pv.yaml
  become: true
  shell: kubectl apply -f nfs-pv.yaml

- name: Copy nfs-pvc.yaml to master
  become: true
  copy:
    src: nfs-pvc.yaml
    dest: ./

- name: Apply nfs-pvc.yaml
  become: true
  shell: kubectl apply -f nfs-pvc.yaml

#- name: Copy webapp-volumes.yaml to master
#  become: true
#  copy:
#    src: webapp-volumes.yaml
#    dest: ./

#- name: apply webapp-volumes.yaml
#  shell: kubectl apply -f webapp-volumes.yaml

##PRUEBAS con varias app

#- name: Copy nginx.yaml
#  ansible.builtin.copy:
#   src: nginx.yaml
#   dest: ./
#   mode: u=rw,g=r,o=r

#- name: Apply nginx.yaml
#  become: true
#  shell: kubectl apply -f nginx.yaml

#- name: Copy loki-stack.yaml
#  ansible.builtin.copy:
#   src: loki-stack.yaml
#   dest: ./
#   mode: u=rw,g=r,o=r

- name: create mamespace
  become: true
  shell: kubectl create namespace wordpress

- name: install helm
  shell: curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3

- name: permissions
  shell: chmod 700 get_helm.sh

- name: install helm
  become: true
  shell: ./get_helm.sh

- name: Helm repo
  become_user: adminUsername
  kubernetes.core.helm_repository:
    name: bitnami
    repo_url: "https://charts.bitnami.com/bitnami"

- name: Copy wordpress-values.yaml to master
  become: true
  copy:
    src: wordpress-values.yaml
    dest: ./

- name: Install wordpress chart
  become_user: adminUsername
  kubernetes.core.helm:
    state: present
    name: wordpress
    release_namespace: wordpress
    chart_ref: bitnami/wordpress
    values_files:
          - ./wordpress-values.yaml