- name: create mamespace
  become: true
  shell: kubectl create namespace webapp-volumes


- name: Copy nfs-pv.yaml to master
  ansible.builtin.copy:
   src: nfs-pv.yaml
   dest: ./
   mode: u=rw,g=r,o=r

- name: Apply nfs-pv.yaml
  become: true
  shell: kubectl apply -f nfs-pv.yaml

- name: Copy nfs-pvc.yaml to master
  become: true
  copy:
    src: nfs-pvc.yaml
    dest: ./

- name: Apply nfs-pvc.yaml
  become: true
  shell: kubectl apply -f nfs-pvc.yaml

- name: Copy webapp-volumes.yaml to master
  become: true
  copy:
    src: webapp-volumes.yaml
    dest: ./

- name: apply webapp-volumes.yaml
  shell: kubectl apply -f webapp-volumes.yaml

##PRUEBAS con varias app

#- name: Copy nginx.yaml
#  ansible.builtin.copy:
#   src: nginx.yaml
#   dest: ./
#   mode: u=rw,g=r,o=r

#- name: Apply nginx.yaml
#  become: true
#  shell: kubectl apply -f nginx.yaml

#- name: Copy loki-stack.yaml
#  ansible.builtin.copy:
#   src: loki-stack.yaml
#   dest: ./
#   mode: u=rw,g=r,o=r

- name: create mamespace
  become: true
  shell: kubectl create namespace loki-stack

- name: install helm
  shell: curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3

- name: permissions
  shell: chmod +x get_helm.sh

#- name: install helm
#  shell: ./get_helm.sh

- name: Apply loki-stack.yaml
  become: true
  become_user: adminUsername
  kubernetes.core.helm_repository:
    name: loki-stack
    repo_url: "https://grafana.github.io/helm-charts"
    release_namespace: loki-stack
    chart_version: 2.5.0
    values_files: loki-stack.yaml



#- name: Add stable chart repo
#  kubernetes.core.helm_repository:
#    name: stable
#    repo_url: "https://kubernetes.github.io/ingress-nginx"