- name: Set timezone
  community.general.timezone:
    name: Europe/Madrid

- name: installing needed packages
  dnf:
    name:
      - wget
      - net-tools
      - nfs-utils
      - chrony
      - python3
      - nfs4-acl-tools
    state: latest

- name: enable chronyd
  systemd:
   name: chronyd
   state: started
   enabled: yes

- name: set ntp
  shell: |
         timedatectl set-ntp true

- name: Disable Selinux
  shell: |
         sed -i s/=enforcing/=disabled/g /etc/selinux/config

- name: Reboot
  reboot:
         reboot_timeout: 3600
         test_command: whoami

